# Generated by Django 3.0.4 on 2020-03-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descibtion',
            new_name='description',
        ),
    ]
